apiVersion: v1
kind: Pod
metadata:
  name: pod-master 
  labels:
    env: test
spec:
  containers:
  - name: ubuntu 
    image: tb15/ubuntu:networkdebug
    imagePullPolicy: IfNotPresent
    command: ["tail"]
    args: ["-f", "/dev/null"]
