apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:0.11-alpine
        ports:
        - name: ghost
          containerPort: 2368
          protocol: TCP
