$ minikube start
Starting local Kubernetes v1.7.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.

$ git clone https://gist.github.com/82c039843663de7e7f1e18bf4debe5fa.git inject-exec-script

$ cd inject-exec-script

$ kubectl create configmap wrapper --from-file=wrapper.sh
configmap "wrapper" created

$ kubectl apply -f deployment.yaml
deployment "ghost" created

$ kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
ghost-3057289974-zvqm8   1/1       Running   0          30s

$ kubectl logs ghost-3057289974-zvqm8
Do my special initialization here then run the regular entrypoint
...
Ghost is running in development...
Listening on 0.0.0.0:2368
Url configured as: http://localhost:2368
Ctrl+C to shut down